### ISSUE TITLE
Add shutdown lock to ConnectionPool

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#105]
`ConnectionPool` registers its own shutdown hook in order to ensure that the connections are released when the JVM dies. This behaviour isn't well documented and some well to do user might register their own shutdown hook to do the same.

Shutdown hooks in Java are run concurrently, so there may be a case of two threads trying to shutdown the pool at the same time.

The easiest fix for this should to change `ConnectionPool#353` to
```java
if(open.compareAndSet(true, false)){
```
in order to ensure that the check is atomic and two threads won't miss updates from each other.

**Comment by jtnelson** [comment]
@hcuffy can you tackle this one? The fix is described above, but I'd also like you to write a unit test for this as well.

**Comment by hcuffy** [comment]
Sure.

**Comment by jtnelson** [comment]
merged
