### ISSUE TITLE
Specify size of collections, where possible, in Concourse Server

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#114]
For the get/select records (and maybe others) we should specify the size of the maps we're using where possible. This means replacing stuff like
```java
Map<Long, Map<String, Set<TObject>>> result = Maps.newLinkedHashMap();
```
with
```java
Map<Long, Map<String, Set<TObject>>> result = TMaps.newLinkedHashMapWithCapacity(records.size());
```

Same thing for Sets, if possible.

**Comment by iamutkarshtiwari** [comment]
@jtnelson Hi, I would like to work on this enhancement. Could you please guide me how to get about it?

P.S- I am new contributor.

**Comment by jtnelson** [comment]
Hi @iamutkarshtiwari, glad to have you aboard as a contributor. For this issue, you'll need to
1. Create a `newLinkedHashMapWithCapacity` method in TMaps.java that'll return a hashmap that is sized according to the input value. 
2. In ConcourseServer.java, look through each of the methods and replace instances where a LinkedHashMap is created with your static factory created above.

**Comment by iamutkarshtiwari** [comment]
@jtnelson I looked into the TMaps.java  and found that the ```newLinkedHashMapWithCapacity``` method already exists in that file which goes by the following definition.

```/**
     * Return <em>mutable</em>, insertion-ordered {@link LinkedHashMap} instance
     * with enough room to fit {@code capacity} items.
     * 
     * <p>
     * Use this method over
     * {@link com.google.common.collect.Maps#newLinkedHashMap()} when the size
     * of the map is known in advance and we are being careful to not oversize
     * collections.
     * </p>
     * 
     * @param capacity the initial capacity
     * @return a new, empty {@link LinkedHashMap}
     */
    public static <K, V> Map<K, V> newLinkedHashMapWithCapacity(int capacity) {
        return new LinkedHashMap<K, V>(capacity);
    } ```

**Comment by jtnelson** [comment]
cool...guess i already wrote it :)

in that case, just need to change all the references in ConcourseServer


*JEFF NELSON*
Founder & CEO
www.cinchapi.com

Follow Cinchapi on Twitter <https://twitter.com/cinchapi> | Github
<https://github.com/cinchapi> | AngelList <https://angel.co/cinchapi>
