### ISSUE TITLE
Should transform value sets lazily

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#124]
Instead of 
```java
                 Map<Long, Set<T>> pretty = PrettyLinkedHashMap
                            .newPrettyLinkedHashMap("Record", key);
                    for (Entry<Long, Set<TObject>> entry : raw.entrySet()) {
                        pretty.put(entry.getKey(), Transformers.transformSet(
                                entry.getValue(),
                                Conversions.<T> thriftToJavaCasted()));
                    }
```
should be doing something like
```java
Map<Long, Set<T>> transformed = Maps.transformValues(raw,
                            TransformFunctions.set(Conversions
                                    .<T> thriftToJavaCasted()));
```
assuming TransformFunctions.set looks like
```java
public static <V1, V2> Function<Set<V1>, Set<V2>> set(
            final Function<V1, V2> function) {
        return new Function<Set<V1>, Set<V2>>() {

            @Override
            public Set<V2> apply(Set<V1> input) {
                return Transformers.transformSet(input, function);
            }

        };
    }
```

Only challenge here is how do we `transformed` to be pretty lazily?

**Comment by chandresh-pancholi** [comment]
Is it fixed?
If not i will start work on it.

**Comment by jtnelson** [comment]
@chandresh-pancholi this one is all yours!

**Comment by jtnelson** [comment]
After reading through this and thinking about it the original goals, I think the best solution is to create a new method in `Transformers` called `#transformSetLazily`. You'll need to create a special kind of `Set` that takes in another `Set` and a transform `Function` and applies the function whenever access is made to an element in the set from the iterator.

For example

```java
class LazyTransformSet<V1, V2> extends AbstractSet<V2> {

public LazyTransformSet(Set<V1> original, Function<V1, V2> function){
...
}

@Override
public Iterator<V2> iterator(){
// Return an iterator that applies the function on each call to next()
}
}
```

**Comment by chandresh-pancholi** [comment]
Below code is also transforming one set to another set using function. 
```
public static <F, V> Set<V> transformSet(Set<F> original,
            Function<? super F, ? extends V> function) {
        Set<V> transformed = Sets.newLinkedHashSetWithExpectedSize(original
                .size());
        for (F item : original) {
            transformed.add(function.apply(item));
        }
        return transformed;
    }
```

**Comment by jtnelson** [comment]
It's not doing it lazily though 

Sent from my iPhone




On Fri, May 27, 2016 at 11:06 PM -0700, "Chandresh Pancholi" <notifications@github.com> wrote:












Below code is also transforming one set to another set using function. 

public static <F, V> Set<V> transformSet(Set<F> original,
            Function<? super F, ? extends V> function) {
        Set<V> transformed = Sets.newLinkedHashSetWithExpectedSize(original
                .size());
        for (F item : original) {
            transformed.add(function.apply(item));
        }
        return transformed;
    }

**Comment by chandresh-pancholi** [comment]
`public class LazyTransformSet<V1, V2> extends AbstractSet<V2>  {
    	
    	private final Set<V1> original;
    	private final Function<V1, V2> function;
    	public LazyTransformSet(Set<V1> original, Function<V1, V2> function){
    		this.original = original;
    		this.function = function;
    	}
    	@SuppressWarnings("unchecked")
		@Override
		public Iterator<V2> iterator() {
			// TODO Auto-generated method stub
			return (Iterator<V2>) function.apply((V1) original);
		}

		@Override
		public int size() {
			// TODO Auto-generated method stub
			return original.size();
		}
    	
    }`

**Comment by chandresh-pancholi** [comment]
Please check.
[public class LazyTransformSet<V1, V2> extends AbstractSet<V2>  {
    	
    	private final Set<V1> original;
    	private final Function<V1, V2> function;
    	public LazyTransformSet(Set<V1> original, Function<V1, V2> function){
    		this.original = original;
    		this.function = function;
    	}
    	@SuppressWarnings("unchecked")
		@Override
		public Iterator<V2> iterator() {
			// TODO Auto-generated method stub
			return (Iterator<V2>) function.apply((V1) original);
		}

		@Override
		public int size() {
			// TODO Auto-generated method stub
			return original.size();
		}
    	
    }](url)

**Comment by jtnelson** [comment]
Your iterator implementation isn't correct. You have to actually create an anonymous iterator that functions correctly. What you have now will throw a classcastexception.
Also, please use pull request for code reviews so we don't pollute people's inboxes with too many comments on issues 

Sent from my iPhone

    _____________________________
