### ISSUE TITLE
SyntaxTools.handleShortSyntax don't work properly in case of mulitple API with API name having underscore case.

### ISSUE THREAD

**Issue by dubex** [cinchapi/concourse#127]
While executing following case : 
callA(record); find_or_add('name', 'concourse'); callB(record"); add('name', 'jeff', 2);

handleShortSyntax() convert find_or_add() to find_or_concourse.add()

ER : concourse.find_or_add()
AR : find_or_concourse.add()

**Comment by jtnelson** [comment]
I can't reproduce the issue.

I added the following unit test to SyntaxToolsTest
```
@Test
    public void reproGH_127(){
        String line = "callA(record); find_or_add('name', 'concourse'); callB(record); add('name', 'jeff', 2);";
        System.out.println(SyntaxTools.handleShortSyntax(line, METHODS));
    }
```
The output was
```
callA(record); find_or_add('name', 'concourse'); callB(record"); add('name', 'jeff', 2);
```

**Comment by jtnelson** [comment]
Am i reproducing the issue correctly?

**Comment by dubex** [comment]
In SyntaxToolsTest, I tried to run test case : 
@Test
    public void reproGH_127(){
        String line = "callA(record); find_or_add('name', 'concourse'); callB(record); add('name', 'jeff', 2);";
        System.out.println(SyntaxTools.handleShortSyntax(line, METHODS));
    }

It gaves the output : callA(record); find_or_add('name', 'concourse'); callB(record"); add('name', 'jeff', 2);

But when, I tried to run test case : 
    @Test
    public void reproGH_127(){
        String line = "callA(record); find_or_add('name', 'concourse'); callB(record); add('name', 'jeff', 2);";
        System.out.println(SyntaxTools.handleShortSyntax(line, ConcourseShell.methods));
    }
Then o/p was callA(record); find_or_concourse.add('name', 'concourse'); callB(record); concourse.add('name', 'jeff', 2);

Note : We need make ConcourseShell.methods public.
