### ISSUE TITLE
Add aliases for query conjunctions

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#134]
Allow CCL statements to contain `||` for OR and `&`/`&&` for AND

**Comment by chandresh-pancholi** [comment]
@jtnelson  Can you please provide brief information about the issue?

**Comment by jtnelson** [comment]
Sure, what info would you like me to provide?

Sent from my iPhone




On Wed, Jun 1, 2016 at 2:58 PM -0700, "Chandresh Pancholi" <notifications@github.com> wrote:












@jtnelson  Can you please provide brief information about the issue?

**Comment by chandresh-pancholi** [comment]
Like where exactly to make change?

**Comment by jtnelson** [comment]
https://github.com/cinchapi/concourse/blob/develop/concourse-server/src/main/java/com/cinchapi/concourse/lang/Parser.java#L204

Take a look at `Parser.java`. I think all you'll need to do is add a clause in the else if blocks on lines 204 and 210 and you should be good. Of course, you'll want to add some unit tests in `ParserTest` and maybe an integration test somewhere in the concourse-integration-tests project as well.

**Comment by chandresh-pancholi** [comment]
@jtnelson Pushed the code and raised a PR. Please check

**Comment by chandresh-pancholi** [comment]
Lets close this issue.
