### ISSUE TITLE
Infinite loop in CaSH

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#135]
```groovy
diff "1452270300424000", time("last week")
```

seems to cause an infinite loop

**Comment by jtnelson** [comment]
@dubex since this is a bug can you work on it before any other issues. Let me know if you don't think you can get it done by the end of this sprint

**Comment by dubex** [comment]
I'm not able to reproduce the issue. I tried to reproduce the issue by adding test case in ConcourseShellTest,

```    @Test
    public void testDiff() throws IrregularEvaluationResult {
       String record = cash.evaluate(" add \"foo\", \"2\"");
       System.out.println(record);
       cash.evaluate("diff \""+record+"\", time(\"last week\")");        
    }
```
Let me know if anything i'm missing.
