### ISSUE TITLE
Fix corner case in handling of short syntax in CaSH

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#139]
Related to GH-135, SyntaxTools is not converting "diff" to concourse.diff in the following input

``` groovy
diff "1452270300424000", time("last week")
```

To fix this, we need to modify the regex in `SyntaxTools#parseShortInvokedMethods` to match any word followed by a paren OR space

**Comment by jtnelson** [comment]
@dubex this is the fix we discussed last week. Just adding it here for tracking purposes

**Comment by dubex** [comment]
Please descibe the test case for which it got reopened. Thanks.

**Comment by jtnelson** [comment]
@dubex same test case, i think i just accidentally closed it the first time and that is why i reopened it

**Comment by jtnelson** [comment]
Same as #465

**Comment by jtnelson** [comment]
Fixed with https://github.com/cinchapi/concourse/commit/f813cd67ebd25c0895a7cb573e65ff8a1da0e759
