### ISSUE TITLE
Link for API missing

### ISSUE THREAD

**Issue by slarrain** [cinchapi/concourse#161]
Hi,
The link for "API" in the main Readme is missing.
Just wanted to let you know.
Keep up the good work.

**Comment by chandresh-pancholi** [comment]
@jtnelson  I can see API link on concoursedb website but it was updated 2 year back.

**Comment by slarrain** [comment]
On the Readme file there is an "Additional Features", inside there is a "API" link and it gives a 404 error.

**Comment by chandresh-pancholi** [comment]
@slarrain We will check and update it by today.

**Comment by jtnelson** [comment]
fix now
