### ISSUE TITLE
Create binary struct object for primitives, lists, sets and maps

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#164]
For the plugin framework, we need a struct that can represent the binary form of a generic object. Right now, `TObject` exists, but it can only encode java primitives. We need something that'll be able to encode primitives in addition to lists, sets and maps.

Here's the approach I'd take:
1. Create a class that wraps a generic `Object` in the concourse-plugin-core project
2. Create a `toByteBuffer` method in the class that will return a byte buffer representation of the wrapped object

For the binary struct, I think the format should be
* type (1 byte)
* payload (n-1 bytes)

**Comment by CompetentSystem** [comment]
I was searching for a project to contribute to. Concourse seems very interesting and I thought I could learn by contributing. But now I realized this is just too hard. I've been programming Java for 3 years now and I think this is far too complex for me. But keep up the great work and good luck, Jeff.  :)

**Comment by jtnelson** [comment]
@CompetentSystem the community can help you dive in with targeted mentorship. This is a large and complex codebase, so even even experienced developers will need some guidance before being able to tackle things. Feel free to email me at jeff [at] cinchapi.com to further discuss how you can ease your way into the project :)

**Comment by chandresh-pancholi** [comment]
@jtnelson  Please assign it to me.

**Comment by jtnelson** [comment]
@chandresh-pancholi i'm almost done with this one, I'll assign another issue to you

**Comment by chandresh-pancholi** [comment]
Sure. I am quite free so i will finish it quickly.
