### ISSUE TITLE
Import validation should check more than just the first line

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#83]
Add logic to validate each line of the import file for conformance with the spec as it is being processed.

**Comment by hcuffy** [comment]
what about something like this (thoughts and research here nothing solid.)
int count =0; 

 do{
BufferedReader br = new BufferedReader(new FileReader(file));
line = br.readline();
count++;

if(line startsWith("<")  && line.endsWith(">"))
   throw new IllegalArgumentException(
            "Csv  file cannot be imported because line" + count +" begins and ends with angle brackets."

}while ((line = br.readline())   != null );

I'm assuming that it will then be placed int he same location as last time or after the logic where the first line is checked. I'm just guessing at this point.

**Comment by jtnelson** [comment]
No need to write logic to actually read the file since thats already taken care of.

In general, implementing this is a relatively simple extension of the `validateFileFormat` method. That method examines a line and decides if the file format is valid. The easiest way to allow validation of multiple lines is to simply remove the `checkedFileFormat` flag in the LineBasedImporter#importFile and each line of the file will be checked.

But if we are checking multiple lines, that allows us to track state that can aide in the validation. In the case of a CSV file, we can evolve the basic validation scheme to something more complex (i.e. ensuring that each line has the same number of fields).

To track state, the class that implements the `validateFileFormat` method would keep variables that recorded whatever it was interested in. So CsvImporter could do something like this

```java
public class CsvImporter extends LineBasedImporter {
    // ...
    private int numCommas = -1; 
    @Override
    protected void validateFileFormat(String line) {
        int numCommas = StringUtils.findMatches(line, delimiter());
        if(this.numCommas < 0) { //this must be the first line we're seeing
            this.numCommas = numCommas;
        }
        else if(numCommas != this.numCommas) {
            throw new IllegalArgumentException(
                    "CSV file cannot be imported when the "
                            + "first line starts and ends with angle brackets");
        }
        else {
    }
}
```

**Comment by hcuffy** [comment]
I understand that we can simply remove the checkedFileFormat boolean in order to go through the entire file. I don't understand how numCommas is working to track angle brackets.  How does counting the delimiter check for angle brackets.

**Comment by hcuffy** [comment]
What the first line needs to be check and the delimiter count saved then each line's number should be compared to the last to ensure the count is the same and threw and error when it's not. Wouldn't we still want to check for angle brackets at least for the first line. And after that checking the delimiter will be checking for CSV validity. The snippet you have up there looks simple and I don't get the findMatches() method. That's i've seen it.

**Comment by jtnelson** [comment]
@hcuffy I don't think we really need to check for angle brackets if we extend to check for the same number of columns in each line. Checking for angle brackets was really just a rudimentary way to check if we'd only consider looking at the first line
