### ISSUE TITLE
Place concourse ctrl script in /etc/init.d so it can be managed by "service" command if OS == Ubuntu/Debian

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#87]
Right now the script is place in /usr/local/bin, which is cool, but a symlink should also be added to /etc/init.d. If we do add this symlink then we must be sure to remove it when the uninstall script is invoked.

**Comment by hcuffy** [comment]
Okay so I went into the  /usr/local/bin via the terminal. There is a concourse file in there. But I can't seem to find the /etc/init.d path. How do I get in there? after i get in there do I: ln -s /usr/local/bin concourse?

Date: Mon, 19 Oct 2015 22:49:06 -0700
